apiVersion: v2
name: bss-backend
description: BSS System Backend - Spring Boot Application
type: application
version: 1.0.0
appVersion: "1.0"

dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
