apiVersion: 1

datasources:
  # Prometheus - Metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus-uid
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    version: 1

  # Tempo - Traces
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo-uid
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogs:
        datasourceUid: 'loki-uid'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [
          { key: 'service.name', value: 'service' }
        ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
      tracesToMetrics:
        datasourceUid: 'prometheus-uid'
        tags: [
          { key: 'service.name', value: 'service' },
          { key: 'job' }
        ]
        queries:
          - name: 'Sample query'
            query: 'sum(rate(traces_spanmetrics_latency_bucket{$$__tags}[5m]))'
      serviceMap:
        datasourceUid: 'prometheus-uid'
      nodeGraph:
        enabled: true
    version: 1

  # Loki - Logs
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    uid: loki-uid
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: 'tempo-uid'
          matcherRegex: '(?:trace_id)=(\w+)'
          name: 'TraceID'
          url: '$${__value.raw}'
        - datasourceUid: 'prometheus-uid'
          matcherRegex: '(?:metric)=(\w+)'
          name: 'Metric'
          url: '$${__value.raw}'
    version: 1

  # Jaeger - Traces (backup)
  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://tempo:16686
    uid: jaeger-uid
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki-uid'
        tags: ['job', 'instance', 'pod', 'namespace']
        mappedTags: [
          { key: 'service.name', value: 'service' }
        ]
        mapTagNamesEnabled: false
        spanStartTimeShift: '1h'
        spanEndTimeShift: '1h'
        filterByTraceID: false
        filterBySpanID: false
    version: 1

  # Elasticsearch - Logs (optional, for production)
  # - name: Elasticsearch
  #   type: elasticsearch
  #   access: proxy
  #   url: http://elasticsearch:9200
  #   uid: elasticsearch-uid
  #   editable: true
  #   jsonData:
  #     index: 'logs-*'
  #     timeField: '@timestamp'
  #   version: 1
