apiVersion: v1
kind: Namespace
metadata:
  name: bss
  labels:
    name: bss
    environment: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bss-backend
  namespace: bss
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/bss-backend-role
