apiVersion: v2
name: bss-backend
description: BSS Backend - Spring Boot Application
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - spring-boot
  - bss
  - backend
home: https://github.com/kanio1/droid-spring
sources:
  - https://github.com/kanio1/droid-spring
